### ISSUE TITLE
No connection gets created

### ISSUE THREAD

**Issue by re8el** [mtbradley/ipvanishvpnmanager#1]
Hi,

Nice script, but I have setup all the files (auth.txt, ca.ipvanish.com.crt)  in path /etc/openvpn i can run the scritp, get the servers, the client.conf, ranked_vpn_server_list.txt gets created.

I have configed the /etc/default/openvpn to client.

But the vpn connection does not get created.

I'm running on Kali linux 2020.2 with python3.

Any ideas ?
tks.

**Comment by mtbradley** [comment]
Just ran a test on Kali 2020.2 - openvpn is more than likely just looking for the /etc/openvpn/up.sh script. If you don't have one just comment the following line (295) vpnmanager.py:

`#ovpn_config_file.write("up /etc/openvpn/up.sh\n")`

I've commented out this line and it ran fine.

If you still have issues try run openvpn manually like so:
`cd /etc/openvpn`
`sudo openvpn client.conf`

This will show any errors which may be stopping the connection being established.
